=== jsanchezv/JSpeccy/src/main/resources/schema/JSpeccy.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/JSpeccy"
    xmlns:tns="http://xml.netbeans.org/schema/JSpeccy">
    <xsd:element name="JSpeccySettings">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="SpectrumSettings" type="tns:SpectrumType"/>
                <xsd:element name="MemorySettings" type="tns:MemoryType"/>
                <xsd:element name="TapeSettings" type="tns:TapeSettingsType"/>
                <xsd:element name="KeyboardJoystickSettings" type="tns:KeyboardJoystickType"/>
                <xsd:element name="AY8912Settings" type="tns:AY8912Type"/>
                <xsd:element name="RecentFilesSettings" type="tns:RecentFilesType"/>
                <xsd:element name="Interface1Settings" type="tns:Interface1Type"/>
                <xsd:element name="EmulatorSettings" type="tns:EmulatorSettingsType"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="SpectrumType">
        <xsd:sequence>
            <xsd:element name="AYEnabled48k" type="xsd:boolean" default="false"/>
            <xsd:element name="mutedSound" type="xsd:boolean" default="false"/>
            <xsd:element name="loadingNoise" type="xsd:boolean" default="true"/>
            <xsd:element name="ULAplus" type="xsd:boolean" default="false"/>
            <xsd:element name="defaultModel" default="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="5"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="framesInt" default="2">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="10"/>
                        <xsd:minInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="zoomed" type="xsd:boolean" default="false"/>
            <xsd:element name="zoom" default="2">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:maxInclusive value="4"/>
                        <xsd:minInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="multifaceEnabled" type="xsd:boolean" default="false"/>
            <xsd:element name="mf128on48K" default="false" type="xsd:boolean"/>
            <xsd:element name="hifiSound" type="xsd:boolean" default="false"/>
            <xsd:element name="hibernateMode" default="false" type="xsd:boolean"/>
            <xsd:element name="lecEnabled" type="xsd:boolean" default="false"/>
            <xsd:element name="emulate128kBug" type="xsd:boolean" default="false"/>
            <xsd:element name="zoomMethod" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:totalDigits value="1"/>
                        <xsd:fractionDigits value="0"/>
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="filterMethod" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:totalDigits value="1"/>
                        <xsd:fractionDigits value="0"/>
                        <xsd:maxInclusive value="2"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="scanLines" type="xsd:boolean" default="false"/>
            <xsd:element name="borderSize" default="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:totalDigits value="1"/>
                        <xsd:fractionDigits value="0"/>
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="3"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="MemoryType">
        <xsd:sequence>
            <xsd:element name="RomsDirectory" type="xsd:string"/>
            <xsd:element name="Rom48k" type="xsd:string" default="spectrum.rom"/>
            <xsd:element name="Rom128k0" type="xsd:string" default="128-0.rom"/>
            <xsd:element name="Rom128k1" type="xsd:string" default="128-1.rom"/>
            <xsd:element name="RomPlus20" type="xsd:string" default="plus2-0.rom"/>
            <xsd:element name="RomPlus21" type="xsd:string" default="plus2-1.rom"/>
            <xsd:element name="RomPlus2a0" default="plus2a-0.rom" type="xsd:string"/>
            <xsd:element name="RomPlus2a1" default="plus2a-1.rom" type="xsd:string"/>
            <xsd:element name="RomPlus2a2" default="plus2a-2.rom" type="xsd:string"/>
            <xsd:element name="RomPlus2a3" default="plus2a-3.rom" type="xsd:string"/>
            <xsd:element name="RomPlus30" type="xsd:string" default="plus3-0.rom"/>
            <xsd:element name="RomPlus31" type="xsd:string" default="plus3-1.rom"/>
            <xsd:element name="RomPlus32" type="xsd:string" default="plus3-2.rom"/>
            <xsd:element name="RomPlus33" type="xsd:string" default="plus3-3.rom"/>
            <xsd:element name="RomMF1" type="xsd:string" default="mf1.rom"/>
            <xsd:element name="RomMF128" type="xsd:string" default="mf128.rom"/>
            <xsd:element name="RomMFPlus3" type="xsd:string" default="mfplus3.rom"/>
            <xsd:element name="RomIF1" default="if1.rom" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TapeSettingsType">
        <xsd:sequence>
            <xsd:element name="enableLoadTraps" type="xsd:boolean" default="true"/>
            <xsd:element name="accelerateLoading" type="xsd:boolean" default="true"/>
            <xsd:element name="enableSaveTraps" type="xsd:boolean" default="true"/>
            <xsd:element name="highSamplingFreq" type="xsd:boolean" default="false"/>
            <xsd:element name="flashLoad" type="xsd:boolean" default="false"/>
            <xsd:element name="autoLoadTape" type="xsd:boolean" default="true"/>
            <xsd:element name="invertedEar" type="xsd:boolean" default="false"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KeyboardJoystickType">
        <xsd:sequence>
            <xsd:element name="JoystickModel" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="5"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="mapPCKeys" default="false" type="xsd:boolean"/>
            <xsd:element name="Issue2" type="xsd:boolean" default="false"/>
            <xsd:element name="recreatedZX" type="xsd:boolean" default="false"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="AY8912Type">
        <xsd:sequence>
            <xsd:element name="soundMode" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="3"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="RecentFilesType">
        <xsd:sequence>
            <xsd:element name="recentFile" type="xsd:string" minOccurs="0" maxOccurs="5"/>
            <xsd:element name="lastSnapshotDir" type="xsd:string"/>
            <xsd:element name="lastTapeDir" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Interface1Type">
        <xsd:sequence>
            <xsd:element name="connectedIF1" default="false" type="xsd:boolean"/>
            <xsd:element name="microdriveUnits" default="8" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:byte">
                        <xsd:maxInclusive value="8"/>
                        <xsd:minInclusive value="1"/>
                        <xsd:totalDigits value="1"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="cartridgeSize" default="180">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="10"/>
                        <xsd:maxInclusive value="254"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="EmulatorSettingsType">
        <xsd:sequence>
            <xsd:element name="confirmActions" type="xsd:boolean" default="true"/>
            <xsd:element name="autosaveConfigOnExit" default="false" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== jsanchezv/JSpeccy/src/main/resources/schema/JSpeccy.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : JSpeccy.xml
    Created on : 30 de noviembre de 2016, 20:58
    Author     : jsanchez
    Description:
        Purpose of the document follows.
-->

<ns0:JSpeccySettings  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                      xmlns:ns0='http://xml.netbeans.org/schema/JSpeccy'
                      xsi:schemaLocation='http://xml.netbeans.org/schema/JSpeccy JSpeccy.xsd'>
    <SpectrumSettings>
        <AYEnabled48k>false</AYEnabled48k>
        <mutedSound>false</mutedSound>
        <loadingNoise>true</loadingNoise>
        <ULAplus>false</ULAplus>
        <defaultModel>1</defaultModel>
        <framesInt>2</framesInt>
        <zoomed>false</zoomed>
        <zoom>2</zoom>
        <multifaceEnabled>false</multifaceEnabled>
        <mf128on48K>false</mf128on48K>
        <hifiSound>false</hifiSound>
        <hibernateMode>false</hibernateMode>
        <lecEnabled>false</lecEnabled>
        <emulate128kBug>false</emulate128kBug>
        <zoomMethod>0</zoomMethod>
        <filterMethod>0</filterMethod>
        <scanLines>false</scanLines>
        <borderSize>1</borderSize>
    </SpectrumSettings>
    <MemorySettings>
        <RomsDirectory></RomsDirectory>
        <Rom48k>spectrum.rom</Rom48k>
        <Rom128k0>128-0.rom</Rom128k0>
        <Rom128k1>128-1.rom</Rom128k1>
        <Rom128kES0>128-0_es.rom</Rom128kES0>
        <Rom128kES1>128-1_es.rom</Rom128kES1>
        <RomPlus20>plus2-0.rom</RomPlus20>
        <RomPlus21>plus2-1.rom</RomPlus21>
        <RomPlus2a0>plus2a-0.rom</RomPlus2a0>
        <RomPlus2a1>plus2a-1.rom</RomPlus2a1>
        <RomPlus2a2>plus2a-2.rom</RomPlus2a2>
        <RomPlus2a3>plus2a-3.rom</RomPlus2a3>
        <RomPlus30>plus3-0.rom</RomPlus30>
        <RomPlus31>plus3-1.rom</RomPlus31>
        <RomPlus32>plus3-2.rom</RomPlus32>
        <RomPlus33>plus3-3.rom</RomPlus33>
        <RomMF1>mf1.rom</RomMF1>
        <RomMF128>mf128.rom</RomMF128>
        <RomMFPlus3>mfplus3.rom</RomMFPlus3>
        <RomIF1>if1.rom</RomIF1>
    </MemorySettings>
    <TapeSettings>
        <enableLoadTraps>true</enableLoadTraps>
        <accelerateLoading>true</accelerateLoading>
        <enableSaveTraps>true</enableSaveTraps>
        <highSamplingFreq>false</highSamplingFreq>
        <flashLoad>false</flashLoad>
        <autoLoadTape>true</autoLoadTape>
        <invertedEar>false</invertedEar>
    </TapeSettings>
    <KeyboardJoystickSettings>
        <JoystickModel>0</JoystickModel>
        <mapPCKeys>false</mapPCKeys>
        <Issue2>false</Issue2>
        <recreatedZX>false</recreatedZX>
    </KeyboardJoystickSettings>
    <AY8912Settings>
        <soundMode>0</soundMode>
    </AY8912Settings>
    <RecentFilesSettings>
        <lastSnapshotDir></lastSnapshotDir>
        <lastTapeDir></lastTapeDir>
    </RecentFilesSettings>
    <Interface1Settings>
        <connectedIF1>false</connectedIF1>
        <microdriveUnits>8</microdriveUnits>
        <cartridgeSize>180</cartridgeSize>
    </Interface1Settings>
    <EmulatorSettings>
        <confirmActions>true</confirmActions>
        <autosaveConfigOnExit>false</autosaveConfigOnExit>
    </EmulatorSettings>

</ns0:JSpeccySettings>
